---
title: "Touring the tidyverse"
subtitle: "Beyond tidyverse"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(magrittr)
```

# tidy projects on CRAN

```{r}
library(magrittr)
res <- tools::CRAN_package_db() %>%
  tibble::as_tibble(.name_repair = "unique") %>%
  dplyr::filter(stringr::str_detect(Package, "tidy") | 
                  stringr::str_detect(Description, "tidy")) %>%
  dplyr::select(Package, Description)

nrow(res)
```
Cleaned up number:

```{r echo = FALSE, message = FALSE}
cleaned <- readr::read_csv("tidyverse/tidy_packages.csv")

nrow(cleaned)
```

---
# Very scientific classification

```{r echo = FALSE}
dplyr::count(cleaned, area, sort = TRUE)  %>%
  dplyr::filter(n > 2) %>%
  gt::gt() 
```

---
# Spotlight

1. `janitor` + `skimr` for data exploration.
1. `tsiblle` for time-series.
1. `tidytext` for NLP.
